name: Run Python Script

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"  # Should be every hour 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Chromium Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxi6 libxcomposite1 libpangocairo-1.0-0 fonts-liberation libappindicator3-1 libatk-bridge2.0-0 libgbm1 libxrandr2 xdg-utils wget

      - name: Clean Output Folder
        run: |
          rm -f output/*.csv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Python Script
        env:
          OUTPUT_DIRECTORY: ${{ github.workspace }}/output
        run: |
          python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          FILE=$(find output -type f -print -quit)
          git add $FILE
          
          git add -u .
          
          git commit -m "automated CSV file downloaded"
          git push
