name: Run Python Script

permissions:
  contents: write

on:
  workflow_dispatch:  # Allows manual trigger via GitHub UI


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clean Output Folder
        run: |
          rm -f output/*.csv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Python Script
        id: download_csv
        env:
          OUTPUT_DIRECTORY: output
        run: |
          python main.py
          echo "CSV_FILE_PATH=$(find $OUTPUT_DIRECTORY -type f -name '*.csv' -print -quit)"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          FILE=$(find output -type f -print -quit)
          git add $FILE
          git commit -m "automated CSV file downloaded???"
          git push
